services:

  pirate-api:
    image: mgc0216/pirate-api:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app
    # restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
