services:

 pirate-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    environment:
      - PORT=8081
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"